### ISSUE TITLE
¿Qué tal va el proyecto?

### ISSUE THREAD

**Issue by JoanBotella** [Obijuan/pyooml#1]
¡Hola Obijuan!

Ayer ví el pequeño video de presentación que colgaste en YouTube, y me animé a echarle un vistazo al repositorio. ¿Qué tal va el proyecto?

Trasteando un poco con el código me han surgido un par de dudas. Soy nuevo tanto en Python como en OpenSCAD, pero a lo mejor puedo ayudar en algo, jeje.
1. He visto que el parámetro center de algunas primitivas de SCAD siempre lo ponéis a `true`, sin permitir que el usuario de la librería pueda modificarlo. ¿Por qué no añadir un parámetro con valor por defecto en el constructor de la clase?
2. También me he fijado en que el SCAD resultante siempre añade la transformación `multimatrix`, aunque no se haya realizado ninguna transformación. ¿Eso no podría obviarse para reducir el tamaño de los SCAD?
3. Otra cosilla es el parámetro `res` de los constructores de las primitivas. Yo mantendría el nombre `fn` (supongo que significa face number o algo así, ¿no?), para no marear a los que vienen de programar en SCAD.

Si el proyecto sigue más o menos activo, y os parece bien, os podría hacer una pequeña _branch_ con los cambios que os comento.

**Comment by Obijuan** [comment]
Hola Joan,

El proyecto ha estado parado durante mucho tiempo. Ahora lo estoy retomando. La idea original es construir una api en un lenguaje de programación genérico para el diseño de piezas. Inicialmente usamos openscad de base, como programa intermedio para poder generar los stls de las piezas e imprimir, pero el objetivo NO es emular openscad. Queremos usar la potencia de un lenguaje orientado a objetos para diseñar objetos físicos. En openscad no hay clases, ni herencias.

Inicialmente implementamos OOML en C++ (Generando código openscad). El inconveniente es que sólo lo podían probar los programadores. La api era complicada y la curva de entrada era alta.  Luego vino pyooml. Mucho más intuitivo y fácil de usar.

El tercer paso es independizarse del código openscad. Estoy haciendo una prueba de concepto usando la api de Freecad, que es nativa de python. Ahora ya se pueden generar objetos sin tener que traducir a código openscad. Te dejo unos enlaces:

 https://www.youtube.com/watch?v=hQoisXgZCuo&list=PLmnz0JqIMEzVo7w2pv6Q04QgRaBTkqR30&index=4

http://www.iearobotics.com/wiki/index.php?title=Videoblog#4_Demo_de_objetos_param.C3.A9tricos_en_Python_desde_Freecad

Creo que ese es el camino para poder desarrollar una mecánica orientada a objetos. Es lo que estoy explorando ahora.

Estoy explorando en este otro repo:

https://github.com/Obijuan/friki

Cuando esté un poco más estable, lo iré integrando en este repo.
